spring:
  application:
    name: simple


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

    open-in-view: true

  datasource:
    url: jdbc:mariadb://localhost:3307/simple
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

